### ISSUE TITLE
OptiX 7.5 support

### ISSUE THREAD

**Issue by Saancreed** [SveSop/wine-nvoptix#22]
Optix `abiId = 60` is out and requires NV driver from r515 branch or newer. Might be a good idea to add support for this version before applications start depending on it.

https://forums.developer.nvidia.com/t/optix-7-5-release/218032

https://raytracing-docs.nvidia.com/optix7/api/optix__function__table_8h_source.html#a38487d5eb99e359b200057df90248e66

**Comment by SveSop** [comment]
I have a fearful notion that the OptiX 7.5 is dependent on CUDA >=11.6 functions - or would expect that. As of now, i have not been successful getting the CUDA RunTime API 11.6 or newer to work with wine, so imo it may be impossible to do any actual testing for this and if my fear is correct, it will not work anyway.

For reference, to get CUDA 11.0 - 11.4 to work, this function is being used: [https://github.com/SveSop/nvcuda/blob/devel/dlls/nvcuda/internal.c#L514-L531](https://github.com/SveSop/nvcuda/blob/devel/dlls/nvcuda/internal.c#L514-L531)
This however fails miserably with CUDA 11.6 (and possibly 11.5.. i have not verified..).

The latest (when i checked) Iray engine for things like DAZ Studio required OptiX 7.4 and CUDA 11.4. If this gets upgraded to OptiX 7.5, i will expect a jump to CUDA 11.6 requirements and that will surely break as it is now.

I am in the middle of moving house these days, and will probably be somewhat tied up in that on/off for a few more weeks, but i can look a bit at it if i get the time to it :smile:  Thanks for the heads up tho :+1:
