### ISSUE TITLE
Suggested buildscript changes

### ISSUE THREAD

**Issue by SveSop** [SveSop/wine-nvoptix#9]
[https://github.com/SveSop/wine-nvoptix/pull/8#pullrequestreview-854682728](https://github.com/SveSop/wine-nvoptix/pull/8#pullrequestreview-854682728)

Keeping a ref here to have this as a work option :smile:

**Comment by SveSop** [comment]
@Saancreed 
I made a new branch - mostly for my separate "nvidia-libs" package. This will put the binaries in `/lib64/wine/` and in their respective `x86_64-unix/windows` subfolder. This is the folderstructure distro wine and Proton-GE uses. I would assume next Proton will follow this suite, since they will most likely move to 7.x version eventually.

I did not create any PR from this branch, since i made it mostly for my own usage.
Atleast it is (to me) a bit less confusing to know where the binaries goes if you decide to copy it into your regular wine install for automagic usage.

I am not sure how the various installers do this - Lutris or Bottles or whatever one use for automation? Do they have their own override scripts based on what you select? I have not used any of them, although briefly tried Bottles in a VM to see if i found it useful.
Do the installscripts for DXVK or VKD3D get used at all by Lutris if you tick a box? Steam uses their own "proton" script to do these things.. Do you know?

**Comment by Saancreed** [comment]
Your branch looks good, though I haven't pulled and tested it locally just yet.

> I would assume next Proton will follow this suite, since they will most likely move to 7.x version eventually.

Yeah, as far as I know Proton is being rebased to 7.0 right now.

> I am not sure how the various installers do this - Lutris or Bottles or whatever one use for automation? Do they have their own override scripts based on what you select? I have not used any of them, although briefly tried Bottles in a VM to see if i found it useful.
> Do the installscripts for DXVK or VKD3D get used at all by Lutris if you tick a box? Steam uses their own "proton" script to do these things.. Do you know?

I have no idea.
